In [1]:
import numpy as np

In [2]:
# 1. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])

with open("day06_1.npz", "wb") as f1:
    np.savez(f1,a=array1,b=array2)
    
f = np.load("day06_1.npz")
print(f.files)
print(f['a'])
print(f['b'])

['a', 'b']
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


In [3]:
# 2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔
array3 = np.array([[4,5,6], [1,2,3]])

f = np.load("day06_1.npz")

with open("day06_2.npz", "wb") as f2:
    np.savez(f2,c=f["a"],d=f["b"],e=array3)
    
f3 = np.load("day06_2.npz")
print(f3.files)
print(f3['c'])
print(f3['d'])
print(f3['e'])

['c', 'd', 'e']
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[[4 5 6]
 [1 2 3]]
